SECTION DATA ; data antes de text
ZERO:	CONST 0
ONE:	CONST 1
OLD:	SPACE
NEW:	SPACE
LIMIT:	SPACE
SECTION DATA ; duplo data
ZERO2: const 2
SECTION TEXT
	COPY ZERO, OLD
	COPY ONE, OLD
	INPUT LIMIT
	OUTPUT OLD
FRONT:	LOAD OLD
	ADD OLD
	STORE NEW
	SUB LIMIT
	JMPP FINAL
	OUTPUT NEW
	COPY OLD, OLD
	COPY NEW, OLD
	JMP FRONT
SECTION TEXT ;duplo text
	one2: const 2 ; const fora do bloco de dados
FINAL:	OUTPUT LIMIT
	STOP
