LABEL EQU 1 ; definicao de equ errado -> vai dar problema
MACRO_LABEL: MACRO &A, &B
	ADD &A
	SUB &B
;macro sem endmacro
SECTION TEXT
	IF LABEL ;label nao vai ser definida -> erro
	COPY ZERO, OLDER
	COPY ONE, OLD
	MACRO ZERO, ONE
	INPUT LIMIT
	OUTPUT OLD
FRONT:	LOAD OLDER
	ADD OLD
	STORE NEW
	SUB LIMIT
	JMPP FINAL
	OUTPUT NEW
	COPY OLD, OLDER
	COPY NEW, OLD
	JMP FRONT
FINAL:	OUTPUT LIMIT
	STOP
SECTION DATA
ZERO:	CONST 0
ONE:	CONST 1
OLDER:	SPACE
OLD:	SPACE
NEW:	SPACE
LIMIT:	SPACE