MACRO_LABEL: MACRO &A, &B
	ADD &A
	SUB &B
ENDMACRO
SECTION TEXT
	COPY ZERO, OLDER
	COPY ONE, OLD
	MACRO_LABEL ZERO ; esperava 2 arguentos
	MACRO_LABEL ZERO, UM, OLDER ; simbolo um nao definido
	MACRO_LABEL ZERO, UM ; um nao definido vai dar problema depois
	INPUT LIMIT
	OUTPUT OLD
FRONT:	LOAD OLDER
	ADD OLD
	STORE NEW
	SUB LIMIT
	JMPP FINAL
	OUTPUT NEW
	COPY OLD, OLDER
	COPY NEW, OLD
	JMP FRONT
FINAL:	OUTPUT LIMIT
	STOP

SECTION DATA
ZERO:	CONST 0
ONE:	CONST 1
OLDER:	SPACE
OLD:	SPACE
NEW:	SPACE
LIMIT:	SPACE