SECTION TEXT
	COPY ZERO, OLDER
	COPY ONE, OLD
FRONT:	LOAD OLDER
	ADD OLD
	STORE NEW
	SUB LIMIT
	COPY NEW, OLD
	JMP FRONT
FINAL:	OUTPUT LIMIT
	STOP 
SECTION DATA
ZERO:	CONST 0A ; deveria ter H no final ou 0x antes
ONE:	CONST 0xAG ; nao é hex
OLDER:	SPACE
OLD:	SPACE
NEW:	SPACE
LIMIT:	SPACE