SECTION TEXT
	COPY ZERO, OLDER ; older nao definido
	COPY ONE, OLD
	INPUT LAD ; lad nao definido
	OUTPUT OLD
FRONT:	LOAD OLDER ; older nao definido
	ADD OLD
	STORE NEW
	SUB LIMIT
	JMPP FINAL
	OUTPUT NEW
	COPY OLD, OLDER ; older nao definido
	COPY NEW, OLD
	JMP FRONT
FINAL:	OUTPUT LIMIT
	STOP
SECTION DATA
ZERO:	CONST 0
ONE:	CONST 1
; Erro por label ausente
;OLDER:	SPACE
OLD:	SPACE
NEW:	SPACE
LIMIT:	SPACE